@REM ===============================================================
@REM =           Generated by JADE Makefile. DO NOT EDIT           =
@REM ===============================================================
echo on
cd src
idltojava -fno-cpp FIPA_Agent_97.idl

call javacc -OUTPUT_DIRECTORY:jade\lang\acl jade\lang\acl\ACLParser.jj
call javacc -OUTPUT_DIRECTORY:jade\domain jade\domain\AgentManagementParser.jj
call javacc -OUTPUT_DIRECTORY:jade\lang\sl jade\lang\sl\SL0Parser.jj
echo on
javac -deprecation -O -d ..\classes jade\Boot.java
javac -deprecation -O -d ..\classes jade\core\behaviours\ComplexBehaviour.java jade\core\behaviours\NonDeterministicBehaviour.java jade\core\behaviours\SequentialBehaviour.java jade\core\behaviours\SimpleBehaviour.java jade\core\behaviours\SenderBehaviour.java jade\core\behaviours\ReceiverBehaviour.java jade\core\behaviours\WakerBehaviour.java jade\domain\SearchDFBehaviour.java jade\proto\ProtocolDrivenBehaviour.java jade\proto\Standard.java jade\proto\FipaRequestInitiatorBehaviour.java jade\proto\FipaRequestResponderBehaviour.java jade\proto\FipaContractNetInitiatorBehaviour.java jade\proto\FipaContractNetResponderBehaviour.java jade\proto\FipaQueryInitiatorBehaviour.java jade\proto\FipaQueryResponderBehaviour.java jade\onto\DefaultOntology.java jade\tools\rma\rma.java jade\tools\sniffer\Sniffer.java jade\tools\DummyAgent\DummyAgent.java jade\tools\SocketProxyAgent\SocketProxyAgent.java jade\applet\DFApplet.java

xcopy /E /I jade\tools\DummyAgent\images ..\classes\jade\tools\DummyAgent\images
xcopy /E /I jade\tools\rma\images ..\classes\jade\tools\rma\images
xcopy /E /I jade\tools\sniffer\images ..\classes\jade\tools\sniffer\images
xcopy /E /I jade\gui\images ..\classes\jade\gui\images

rmic -d ..\classes jade.core.AgentContainerImpl jade.core.AgentPlatformImpl

cd examples
set CLASSPATH=..;..\..\classes
javac -deprecation -d ..\..\classes ex1\Agent1.java ex1\Agent2.java ex1\Agent3.java ex1\Agent4.java ex2\AgentSender.java ex2\AgentReceiver.java ex2\AgentBroadcaster.java ex2\AgentTimeout.java ex2\AboutDialog.java ex2\SentReceivedGUI.java ex2\FilebasedSenderAgent.java ex3\AgentMessageFilter.java ex3\AgentThread.java ex4\AgentRequester.java ex4\AgentResponder.java ex5\amsTester.java ex5\dfTester.java ex5\SubDF.java ex5\MobileAgent.java ex6\AgQueryInit.java ex6\AgQueryResp.java ex7\ObjectReaderAgent.java ex7\ObjectWriterAgent.java ex7\OntologyTest.java ex_mobile\MobileAgent.java jess\JessAgent.java ex8\WakerExampleAgent.java
cd ..\..

pause



