@REM ===============================================================
@REM =           Generated by JADE Makefile. DO NOT EDIT           =
@REM ===============================================================

rmdir /S /Q classes\*
deltree /Y classes\*
del .\doc\api\*.html
del .\doc\api\*.css
del .\doc\api\*.
rmdir /S /Q .\doc\api\jade
deltree /Y .\doc\api\jade
del .\doc\tools\sniffer\html\jdoc\*.html
del .\doc\tools\sniffer\html\jdoc\*.css
del .\doc\tools\sniffer\html\jdoc\*.
rmdir /S /Q .\doc\tools\sniffer\html\jdoc\jade
deltree /Y .\doc\tools\sniffer\html\jdoc\jade
del .\lib\jadeTools.jar
del .\lib\jade.jar
del .\lib\Base64.jar
