@REM ===============================================================
@REM =           Generated by JADE Makefile. DO NOT EDIT           =
@REM ===============================================================

cd src
idltojava -fno-cpp FIPA_Agent_97.idl

call javacc -OUTPUT_DIRECTORY:jade\lang\acl jade\lang\acl\ACLParser.jj
call javacc -OUTPUT_DIRECTORY:jade\domain jade\domain\AgentManagementParser.jj
call javacc -OUTPUT_DIRECTORY:jade\lang\sl jade\lang\sl\SL0Parser.jj

javac -deprecation -O -d ..\classes jade\Boot.java
javac -deprecation -O -d ..\classes jade\core\behaviours\ComplexBehaviour.java jade\core\behaviours\NonDeterministicBehaviour.java jade\core\behaviours\SequentialBehaviour.java jade\core\behaviours\SimpleBehaviour.java jade\core\behaviours\SenderBehaviour.java jade\core\behaviours\ReceiverBehaviour.java jade\core\behaviours\WakerBehaviour.java jade\domain\SearchDFBehaviour.java jade\proto\ProtocolDrivenBehaviour.java jade\proto\Standard.java jade\proto\FipaRequestInitiatorBehaviour.java jade\proto\FipaRequestResponderBehaviour.java jade\proto\FipaContractNetInitiatorBehaviour.java jade\proto\FipaContractNetResponderBehaviour.java jade\proto\FipaQueryInitiatorBehaviour.java jade\proto\FipaQueryResponderBehaviour.java jade\onto\DefaultOntology.java jade\tools\rma\rma.java jade\tools\sniffer\Sniffer.java jade\tools\DummyAgent\DummyAgent.java jade\tools\SocketProxyAgent\SocketProxyAgent.java jade\tools\applet\DFApplet.java

xcopy /E /I jade\tools\DummyAgent\images ..\classes\jade\tools\DummyAgent\images
xcopy /E /I jade\tools\rma\images ..\classes\jade\tools\rma\images
xcopy /E /I jade\tools\sniffer\images ..\classes\jade\tools\sniffer\images
xcopy /E /I jade\gui\images ..\classes\jade\gui\images

rmic -d ..\classes jade.core.AgentContainerImpl jade.core.AgentPlatformImpl

cd ..
