@REM ===============================================================
@REM =           Generated by JADE Makefile. DO NOT EDIT           =
@REM ===============================================================

cd .\classes
jar cvf ..\lib\jadeTools.jar jade\tools
rmdir /S /Q jade\tools
deltree /Y jade\tools

jar cvf ..\lib\jade.jar *.class jade
rmdir /S /Q  jade
deltree /Y  jade
del *.class

jar cvf ..\lib\Base64.jar starlight
rmdir /S /Q starlight
deltree /Y starlight
cd ..
