@REM ===============================================================
@REM =           Generated by JADE Makefile. DO NOT EDIT           =
@REM ===============================================================

echo on
cd ..
jar cMvf JADE-src-1.3.zip jade\README jade\License jade\COPYING jade\*.bat jade\Makefile jade\src\Makefile jade\src\*.idl jade\src\jade
cd jade
cd ..
jar cMvf JADE-examples-1.3.zip jade\README jade\License jade\COPYING jade\src\examples jade\src\demo
cd jade
call .\makedoc.bat
cd ..
jar cMvf JADE-doc-1.3.zip jade\README jade\License jade\COPYING jade\doc
cd jade
call .\makejade.bat
call .\makelib.bat
cd ..
jar cMvf JADE-bin-1.3.zip jade\README jade\License jade\COPYING jade\lib jade\src\starlight
cd jade
cd ..
jar cMvf JADE-all-1.3.zip JADE-src-1.3.zip JADE-examples-1.3.zip JADE-doc-1.3.zip JADE-bin-1.3.zip