@REM ===============================================================
@REM =           Generated by JADE Makefile. DO NOT EDIT           =
@REM ===============================================================

javadoc -sourcepath .\src -d .\doc\api -overview .\src\jade-main.html -author -windowtitle "JADE 1.3 API Reference" jade jade.core jade.core.behaviours jade.lang.acl jade.domain jade.proto jade.gui

javadoc -sourcepath .\src -d .\doc\tools\sniffer\html\jdoc -author -windowtitle "JADE 1.3 Sniffer Reference" jade.tools.sniffer

