// Generated by Together/J
package demo.MeetingScheduler.CLP;
/**
 * This class implements a multivalue of the ontology. 
 * @see OntologyObject
 */
public class MultiValue extends OntologyObject {    
public MultiValue(){
super();
setType(MULTIVALUE_TYPE);
}

  /**
   * adds a value that is a String 
   */
public void addValue(String val) {
SimpleValue obj = new SimpleValue();
obj.setValue(val);
addValue(obj);
}

  /**
   * adds a value that is an OntologyObject
   */
public void addValue (OntologyObject val){
addSlot(Integer.toString(getNumberOfValues()),val);
}

  /**
   * returns the number of values in this multislot object
   */
public int getNumberOfValues(){
return getNumberOfSlots();
}

  /**
   * returns an OntologyObject representing the value in the given position
   */
public OntologyObject getValue (int position) {
return getSlot(Integer.toString(position));
}

  /**
   * returns the multi value as a String. The returned String complies with the
   * factsA1CL content language, as specified in the deliverable A12D1
   */
  public String toString() {
   int i;
   if (getValue(0).getType() == ACTION_TYPE)
    return "(" + getValue(0).toString()+" " +getValue(1).toString()+")";
   String str = "";
   for (i=0; i<getNumberOfValues(); i++)
    str = str + " " + getValue(i).toString();
   return str;
  }  
}


