// Generated by Together/J
package demo.MeetingScheduler.CLP;

/**
 * This class implements an object descriptor of the ontology (i.e. the iota operator)
 * @see OntologyObject
 */
public class ObjectDescriptor extends OntologyObject {
  private int iotapattern;

public ObjectDescriptor() {
super();
setType(OBJECTDESCRIPTOR_TYPE);
}
  
  /** 
   * returns the name of the variable bound to the iota operator
   */
  public String getObjectName(){
return getName();
  }

  /**
   * bound the iota operator to the given variable name
   */
  public void setObjectName(String name){
setName(name);
  }
  
  /**
   * sets the position of the pattern to which the iota variable has been bound
   */
  public void setIotaPattern(int patternnumber) {
    this.iotapattern = patternnumber;
  }

  /**
   * returns the position of the pattern to which the iota variable has been bound
   */
  public int getIotaPattern(){
    return iotapattern;
  }                            
                         
  /**
   * returns a Proposition encoding the Object description
   */                    
  public Proposition getDescription() {
    return (Proposition)getSlot("0");
  }
  
  /**
   * sets the Object Description encoded as a Proposition
   */
public void addDescription(Proposition p){
 addSlot("0",p);
}

  /**
   * returns the object descriptor as a String. The returned String complies with the
   * factsA1CL content language, as specified in the deliverable A12D1
   */
  public String toString() {   
   String str = "(iota "+getName()+" " + getDescription().toString();;
   if (getIotaPattern()>-1) str = str + "\nIotaVariable is bound to Pattern "+getIotaPattern();
   return str;
  }  
}




