// Generated by Together/J
package demo.MeetingScheduler.CLP;


/**
 * This class implements a proposition of the ontology. 
 * @see OntologyObject
 */
public class Proposition extends OntologyObject { 
public Proposition() {
super();
setType(PROPOSITION_TYPE);
}

  /**
   * returns the predicate name
   */
  public String getName() {
return super.getName();
  }

  /**
   * sets the predicate name
   */
  public void setName(String name){
super.setName(name);
  }  

  /**
   * add a Term to the proposition
   */
  public void addTerm(OntologyObject term){
addSlot(Integer.toString(getNumberOfSlots()),term);
  }

  /** 
   * returns the number of Terms of this proposition
   */
  public int getNumberOfTerms(){
return getNumberOfSlots();
  }  

  /**
   * return the OntologyObject representing the term in the given position
   * @param position is the ordinal position
   */       
  public OntologyObject getTerm(int position) {
return getSlot(Integer.toString(position));
  }

  /**
   * returns the proposition as a String. The returned String complies with the
   * factsA1CL content language, as specified in the deliverable A12D1
   */
  public String toString() {
   if (getNumberOfTerms() == 0) return getName();
   String str = "(" + getName();
   for (int i=0; i<getNumberOfTerms(); i++)
    str = str + " " + getTerm(i).toString();
   return str + ")";
  }  
}




