// Generated by Together/J
package demo.MeetingScheduler.CLP;
public class SimpleValue extends OntologyObject {
/**
 * This class implements a single value of the ontology. 
 * @see OntologyObject
 */
public SimpleValue(){
 super();
 setType(SIMPLEVALUE_TYPE);
}
  /**
   * gets the value
   */
  public String getValue(){ 
  return getName();
  }  

  /** 
   * sets the value
   */
  public void setValue(String val){
  setName(val);
  }
  /**
   * returns the simple value as a String. The returned String complies with the
   * factsA1CL content language, as specified in the deliverable A12D1
   */
  public String toString() {
  return getName();
  }  
  }




