/* Generated By:JavaCC: Do not edit this line. SL0ParserConstants.java */
/* $Id: SL0Parser.jj,v 1.2 1999/01/29 06:22:05 bellifemine Exp bellifemine $

   $Log: SL0Parser.jj,v $
   Revision 1.2  1999/01/29 06:22:05  bellifemine
   <>

   Revision 1.1  1999/01/29 03:33:28  bellifemine
   Initial revision

   Revision 1.1  1999/01/18 15:44:47  bellifemine
   Initial revision

   Revision 1.2  1998/12/16 12:52:50  bellifemine
   Removed bug in OntologyObject.toString()

   Revision 1.1  1998/12/14 11:58:58  bellifemine
   Initial revision

*/

package demo.MeetingScheduler.CLP;

public interface SL0ParserConstants {

  int EOF = 0;
  int LBRACE = 5;
  int RBRACE = 6;
  int ACTION = 7;
  int DONE = 8;
  int IOTA = 9;
  int DATE = 10;
  int DATETIME = 11;
  int WORD = 12;
  int STRINGLITERAL = 13;
  int INTEGER = 14;
  int FLOATONE = 15;
  int FLOATTWO = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"action\"",
    "\"done\"",
    "\"iota\"",
    "<DATE>",
    "<DATETIME>",
    "<WORD>",
    "<STRINGLITERAL>",
    "<INTEGER>",
    "<FLOATONE>",
    "<FLOATTWO>",
  };

}
