# Makefile for Agent Development Kit project - lib directory

# The following targets are not file names
.PHONY: all clean

TARGETS =

all: 
	@echo Making library ...
clean:
	rm -f `find . -name '*~' -print`
	rm -f `find . -name '#*#' -print`
	rm -f `find . -name '*.class' -print`


