/* Generated By:JavaCC: Do not edit this line. SL0ParserConstants.java */
package jade.lang.sl;

public interface SL0ParserConstants {

  int EOF = 0;
  int LBRACE = 5;
  int RBRACE = 6;
  int ACTION = 7;
  int INTEGER = 8;
  int HEXINTEGER = 9;
  int FLOATONE = 10;
  int FLOATTWO = 11;
  int WORD = 12;
  int STRING_LITERAL = 13;
  int PARAMETERNAME = 14;
  int DATETIME = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"action\"",
    "<INTEGER>",
    "<HEXINTEGER>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<WORD>",
    "<STRING_LITERAL>",
    "<PARAMETERNAME>",
    "<DATETIME>",
  };

}
