package FIPA;


/**
* FIPA/_MTSImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from fipa.idl
* martedì 14 agosto 2001 12.58.13 GMT+02:00
*/

public abstract class _MTSImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements FIPA.MTS, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _MTSImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("message", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FIPA/MTS/message
       {
         FIPA.FipaMessage aFipaMessage = FIPA.FipaMessageHelper.read (in);
         this.message (aFipaMessage);
         out = rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FIPA/MTS:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _MTSImplBase
