package FIPA;


/**
* FIPA/AgentIDsHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/

public final class AgentIDsHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.AgentID value[] = null;

  public AgentIDsHolder ()
  {
  }

  public AgentIDsHolder (FIPA.AgentID[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.AgentIDsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.AgentIDsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.AgentIDsHelper.type ();
  }

}
