package FIPA;

/**
* FIPA/AgentIDHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from fipa.idl
* martedì 14 agosto 2001 12.58.13 GMT+02:00
*/

public final class AgentIDHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.AgentID value = null;

  public AgentIDHolder ()
  {
  }

  public AgentIDHolder (FIPA.AgentID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.AgentIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.AgentIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.AgentIDHelper.type ();
  }

}
