package FIPA;


/**
* FIPA/DateTimeHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/


// to the local timezone.
abstract public class DateTimeHelper
{
  private static String  _id = "IDL:FIPA/DateTime:1.0";

  public static void insert (org.omg.CORBA.Any a, FIPA.DateTime that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FIPA.DateTime extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [8];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "year",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "month",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[2] = new org.omg.CORBA.StructMember (
            "day",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[3] = new org.omg.CORBA.StructMember (
            "hour",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[4] = new org.omg.CORBA.StructMember (
            "minutes",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[5] = new org.omg.CORBA.StructMember (
            "seconds",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[6] = new org.omg.CORBA.StructMember (
            "milliseconds",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_char);
          _members0[7] = new org.omg.CORBA.StructMember (
            "typeDesignator",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FIPA.DateTimeHelper.id (), "DateTime", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FIPA.DateTime read (org.omg.CORBA.portable.InputStream istream)
  {
    FIPA.DateTime value = new FIPA.DateTime ();
    value.year = istream.read_short ();
    value.month = istream.read_short ();
    value.day = istream.read_short ();
    value.hour = istream.read_short ();
    value.minutes = istream.read_short ();
    value.seconds = istream.read_short ();
    value.milliseconds = istream.read_short ();
    value.typeDesignator = istream.read_char ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FIPA.DateTime value)
  {
    ostream.write_short (value.year);
    ostream.write_short (value.month);
    ostream.write_short (value.day);
    ostream.write_short (value.hour);
    ostream.write_short (value.minutes);
    ostream.write_short (value.seconds);
    ostream.write_short (value.milliseconds);
    ostream.write_char (value.typeDesignator);
  }

}
