package FIPA;


/**
* FIPA/EnvelopesHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/

public final class EnvelopesHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.Envelope value[] = null;

  public EnvelopesHolder ()
  {
  }

  public EnvelopesHolder (FIPA.Envelope[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.EnvelopesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.EnvelopesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.EnvelopesHelper.type ();
  }

}
