package FIPA;


/**
* FIPA/EnvelopeHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/

abstract public class EnvelopeHelper
{
  private static String  _id = "IDL:FIPA/Envelope:1.0";

  public static void insert (org.omg.CORBA.Any a, FIPA.Envelope that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FIPA.Envelope extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [12];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = FIPA.AgentIDHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.AgentIDsHelper.id (), "AgentIDs", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "to",
            _tcOf_members0,
            null);
          _tcOf_members0 = FIPA.AgentIDHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (1, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.OptAgentIDHelper.id (), "OptAgentID", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "from",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "comments",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "aclRepresentation",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "payloadLength",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "payloadEncoding",
            _tcOf_members0,
            null);
          _tcOf_members0 = FIPA.DateTimeHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (1, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.OptDateTimeHelper.id (), "OptDateTime", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "date",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.stringsHelper.id (), "strings", _tcOf_members0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "encrypted",
            _tcOf_members0,
            null);
          _tcOf_members0 = FIPA.AgentIDHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.AgentIDsHelper.id (), "AgentIDs", _tcOf_members0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "intendedReceiver",
            _tcOf_members0,
            null);
          _tcOf_members0 = FIPA.ReceivedObjectHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (1, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.OptReceivedObjectHelper.id (), "OptReceivedObject", _tcOf_members0);
          _members0[9] = new org.omg.CORBA.StructMember (
            "received",
            _tcOf_members0,
            null);
          _tcOf_members0 = FIPA.PropertyHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.TransportBehaviourTypeHelper.id (), "TransportBehaviourType", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (1, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.OptTransportBehaviourTypeHelper.id (), "OptTransportBehaviourType", _tcOf_members0);
          _members0[10] = new org.omg.CORBA.StructMember (
            "transportBehaviour",
            _tcOf_members0,
            null);
          _tcOf_members0 = FIPA.PropertyHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[11] = new org.omg.CORBA.StructMember (
            "userDefinedProperties",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FIPA.EnvelopeHelper.id (), "Envelope", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FIPA.Envelope read (org.omg.CORBA.portable.InputStream istream)
  {
    FIPA.Envelope value = new FIPA.Envelope ();
    value.to = FIPA.AgentIDsHelper.read (istream);
    value.from = FIPA.OptAgentIDHelper.read (istream);
    value.comments = istream.read_string ();
    value.aclRepresentation = istream.read_string ();
    value.payloadLength = istream.read_long ();
    value.payloadEncoding = istream.read_string ();
    value.date = FIPA.OptDateTimeHelper.read (istream);
    value.encrypted = FIPA.stringsHelper.read (istream);
    value.intendedReceiver = FIPA.AgentIDsHelper.read (istream);
    value.received = FIPA.OptReceivedObjectHelper.read (istream);
    value.transportBehaviour = FIPA.OptTransportBehaviourTypeHelper.read (istream);
    int _len0 = istream.read_long ();
    value.userDefinedProperties = new FIPA.Property[_len0];
    for (int _o1 = 0;_o1 < value.userDefinedProperties.length; ++_o1)
      value.userDefinedProperties[_o1] = FIPA.PropertyHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FIPA.Envelope value)
  {
    FIPA.AgentIDsHelper.write (ostream, value.to);
    FIPA.OptAgentIDHelper.write (ostream, value.from);
    ostream.write_string (value.comments);
    ostream.write_string (value.aclRepresentation);
    ostream.write_long (value.payloadLength);
    ostream.write_string (value.payloadEncoding);
    FIPA.OptDateTimeHelper.write (ostream, value.date);
    FIPA.stringsHelper.write (ostream, value.encrypted);
    FIPA.AgentIDsHelper.write (ostream, value.intendedReceiver);
    FIPA.OptReceivedObjectHelper.write (ostream, value.received);
    FIPA.OptTransportBehaviourTypeHelper.write (ostream, value.transportBehaviour);
    ostream.write_long (value.userDefinedProperties.length);
    for (int _i0 = 0;_i0 < value.userDefinedProperties.length; ++_i0)
      FIPA.PropertyHelper.write (ostream, value.userDefinedProperties[_i0]);
  }

}
