package FIPA;


/**
* FIPA/Envelope.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from fipa.idl
* martedì 14 agosto 2001 12.58.13 GMT+02:00
*/

public final class Envelope implements org.omg.CORBA.portable.IDLEntity
{
  public FIPA.AgentID to[] = null;
  public FIPA.AgentID from[] = null;
  public String comments = null;
  public String aclRepresentation = null;
  public int payloadLength = (int)0;
  public String payloadEncoding = null;
  public FIPA.DateTime date[] = null;
  public String encrypted[] = null;
  public FIPA.AgentID intendedReceiver[] = null;
  public FIPA.ReceivedObject received[] = null;
  public FIPA.Property transportBehaviour[][] = null;
  public FIPA.Property userDefinedProperties[] = null;

  public Envelope ()
  {
  } // ctor

  public Envelope (FIPA.AgentID[] _to, FIPA.AgentID[] _from, String _comments, String _aclRepresentation, int _payloadLength, String _payloadEncoding, FIPA.DateTime[] _date, String[] _encrypted, FIPA.AgentID[] _intendedReceiver, FIPA.ReceivedObject[] _received, FIPA.Property[][] _transportBehaviour, FIPA.Property[] _userDefinedProperties)
  {
    to = _to;
    from = _from;
    comments = _comments;
    aclRepresentation = _aclRepresentation;
    payloadLength = _payloadLength;
    payloadEncoding = _payloadEncoding;
    date = _date;
    encrypted = _encrypted;
    intendedReceiver = _intendedReceiver;
    received = _received;
    transportBehaviour = _transportBehaviour;
    userDefinedProperties = _userDefinedProperties;
  } // ctor

} // class Envelope
