package FIPA;


/**
* FIPA/FipaMessageHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/

abstract public class FipaMessageHelper
{
  private static String  _id = "IDL:FIPA/FipaMessage:1.0";

  public static void insert (org.omg.CORBA.Any a, FIPA.FipaMessage that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FIPA.FipaMessage extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = FIPA.EnvelopeHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.EnvelopesHelper.id (), "Envelopes", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "messageEnvelopes",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.PayloadHelper.id (), "Payload", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "messageBody",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FIPA.FipaMessageHelper.id (), "FipaMessage", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FIPA.FipaMessage read (org.omg.CORBA.portable.InputStream istream)
  {
    FIPA.FipaMessage value = new FIPA.FipaMessage ();
    value.messageEnvelopes = FIPA.EnvelopesHelper.read (istream);
    value.messageBody = FIPA.PayloadHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FIPA.FipaMessage value)
  {
    FIPA.EnvelopesHelper.write (ostream, value.messageEnvelopes);
    FIPA.PayloadHelper.write (ostream, value.messageBody);
  }

}
