package FIPA;


/**
* FIPA/FipaMessage.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/

public final class FipaMessage implements org.omg.CORBA.portable.IDLEntity
{
  public FIPA.Envelope messageEnvelopes[] = null;
  public byte messageBody[] = null;

  public FipaMessage ()
  {
  } // ctor

  public FipaMessage (FIPA.Envelope[] _messageEnvelopes, byte[] _messageBody)
  {
    messageEnvelopes = _messageEnvelopes;
    messageBody = _messageBody;
  } // ctor

} // class FipaMessage
