package FIPA;


/**
* FIPA/FipaMessage.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from fipa.idl
* martedì 14 agosto 2001 12.58.13 GMT+02:00
*/

public final class FipaMessage implements org.omg.CORBA.portable.IDLEntity
{
  public FIPA.Envelope messageEnvelopes[] = null;
  public byte messageBody[] = null;

  public FipaMessage ()
  {
  } // ctor

  public FipaMessage (FIPA.Envelope[] _messageEnvelopes, byte[] _messageBody)
  {
    messageEnvelopes = _messageEnvelopes;
    messageBody = _messageBody;
  } // ctor

} // class FipaMessage
