package FIPA;


/**
* FIPA/MTSHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/

abstract public class MTSHelper
{
  private static String  _id = "IDL:FIPA/MTS:1.0";

  public static void insert (org.omg.CORBA.Any a, FIPA.MTS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FIPA.MTS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FIPA.MTSHelper.id (), "MTS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FIPA.MTS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MTSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FIPA.MTS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FIPA.MTS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FIPA.MTS)
      return (FIPA.MTS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FIPA._MTSStub stub = new FIPA._MTSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
