package FIPA;


/**
* FIPA/OptAgentIDHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/


// Using bounded sequences with size of 1 to model optional slots
public final class OptAgentIDHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.AgentID value[] = null;

  public OptAgentIDHolder ()
  {
  }

  public OptAgentIDHolder (FIPA.AgentID[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.OptAgentIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.OptAgentIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.OptAgentIDHelper.type ();
  }

}
