package FIPA;


/**
* FIPA/OptReceivedObjectHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from fipa.idl
* martedì 14 agosto 2001 12.58.13 GMT+02:00
*/

public final class OptReceivedObjectHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.ReceivedObject value[] = null;

  public OptReceivedObjectHolder ()
  {
  }

  public OptReceivedObjectHolder (FIPA.ReceivedObject[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.OptReceivedObjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.OptReceivedObjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.OptReceivedObjectHelper.type ();
  }

}
