package FIPA;


/**
* FIPA/PayloadHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/

public final class PayloadHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public PayloadHolder ()
  {
  }

  public PayloadHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.PayloadHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.PayloadHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.PayloadHelper.type ();
  }

}
