package FIPA;


/**
* FIPA/Property.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.11 CET
*/


// keyword and value pair.
public final class Property implements org.omg.CORBA.portable.IDLEntity
{
  public String keyword = null;
  public org.omg.CORBA.Any value = null;

  public Property ()
  {
  } // ctor

  public Property (String _keyword, org.omg.CORBA.Any _value)
  {
    keyword = _keyword;
    value = _value;
  } // ctor

} // class Property
