package FIPA;


/**
* FIPA/Property.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from fipa.idl
* martedì 14 agosto 2001 12.58.13 GMT+02:00
*/


// keyword and value pair.
public final class Property implements org.omg.CORBA.portable.IDLEntity
{
  public String keyword = null;
  public org.omg.CORBA.Any value = null;

  public Property ()
  {
  } // ctor

  public Property (String _keyword, org.omg.CORBA.Any _value)
  {
    keyword = _keyword;
    value = _value;
  } // ctor

} // class Property
