package FIPA;


/**
* FIPA/ReceivedObjectHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from fipa.idl
* martedì 14 agosto 2001 12.58.13 GMT+02:00
*/

abstract public class ReceivedObjectHelper
{
  private static String  _id = "IDL:FIPA/ReceivedObject:1.0";

  public static void insert (org.omg.CORBA.Any a, FIPA.ReceivedObject that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FIPA.ReceivedObject extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.URLHelper.id (), "URL", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "by",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FIPA.URLHelper.id (), "URL", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "from",
            _tcOf_members0,
            null);
          _tcOf_members0 = FIPA.DateTimeHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "date",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "via",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FIPA.ReceivedObjectHelper.id (), "ReceivedObject", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FIPA.ReceivedObject read (org.omg.CORBA.portable.InputStream istream)
  {
    FIPA.ReceivedObject value = new FIPA.ReceivedObject ();
    value.by = istream.read_string ();
    value.from = istream.read_string ();
    value.date = FIPA.DateTimeHelper.read (istream);
    value.id = istream.read_string ();
    value.via = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FIPA.ReceivedObject value)
  {
    ostream.write_string (value.by);
    ostream.write_string (value.from);
    FIPA.DateTimeHelper.write (ostream, value.date);
    ostream.write_string (value.id);
    ostream.write_string (value.via);
  }

}
