package FIPA;


/**
* FIPA/TransportBehaviourTypeHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from fipa.idl
* venerdì 7 dicembre 2001 16.57.12 CET
*/

public final class TransportBehaviourTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.Property value[] = null;

  public TransportBehaviourTypeHolder ()
  {
  }

  public TransportBehaviourTypeHolder (FIPA.Property[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.TransportBehaviourTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.TransportBehaviourTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.TransportBehaviourTypeHelper.type ();
  }

}
