/* Generated By:JavaCC: Do not edit this line. ExtendedSLParserConstants.java */
package jade.content.lang.sl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExtendedSLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 5;
  /** RegularExpression Id. */
  int RBRACE = 6;
  /** RegularExpression Id. */
  int VARIABLE = 7;
  /** RegularExpression Id. */
  int REFERENCE = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int HEXINTEGER = 10;
  /** RegularExpression Id. */
  int LONG = 11;
  /** RegularExpression Id. */
  int FLOATONE = 12;
  /** RegularExpression Id. */
  int FLOATTWO = 13;
  /** RegularExpression Id. */
  int FLOAT = 14;
  /** RegularExpression Id. */
  int WORD = 15;
  /** RegularExpression Id. */
  int STRING_LITERAL = 16;
  /** RegularExpression Id. */
  int PARAMETERNAME = 17;
  /** RegularExpression Id. */
  int PARAMETERNAME_STRING = 18;
  /** RegularExpression Id. */
  int DATETIME = 19;
  /** RegularExpression Id. */
  int PREFIXBYTELENGTHENCODEDSTRING = 20;
  /** RegularExpression Id. */
  int METASYMBOL = 21;
  /** RegularExpression Id. */
  int LBRACE2 = 26;
  /** RegularExpression Id. */
  int RBRACE2 = 27;
  /** RegularExpression Id. */
  int ACTION = 28;
  /** RegularExpression Id. */
  int REFERENTIALOP = 29;
  /** RegularExpression Id. */
  int MODALOP = 30;
  /** RegularExpression Id. */
  int ARITHMETICOP = 31;
  /** RegularExpression Id. */
  int ACTIONOP = 32;
  /** RegularExpression Id. */
  int ACTIONOPLL = 33;
  /** RegularExpression Id. */
  int UNARYLOGICALOP = 34;
  /** RegularExpression Id. */
  int BINARYLOGICALOP = 35;
  /** RegularExpression Id. */
  int QUANTIFIER = 36;
  /** RegularExpression Id. */
  int CONDITIONEDQUANTIFIER = 37;
  /** RegularExpression Id. */
  int WORD2 = 38;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 39;
  /** RegularExpression Id. */
  int METASYMBOL2 = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int OPERATORSTATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "<VARIABLE>",
    "<REFERENCE>",
    "<INTEGER>",
    "<HEXINTEGER>",
    "<LONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<FLOAT>",
    "<WORD>",
    "<STRING_LITERAL>",
    "<PARAMETERNAME>",
    "<PARAMETERNAME_STRING>",
    "<DATETIME>",
    "<PREFIXBYTELENGTHENCODEDSTRING>",
    "<METASYMBOL>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"action\"",
    "<REFERENTIALOP>",
    "<MODALOP>",
    "<ARITHMETICOP>",
    "<ACTIONOP>",
    "<ACTIONOPLL>",
    "\"not\"",
    "<BINARYLOGICALOP>",
    "<QUANTIFIER>",
    "\"foreach\"",
    "<WORD2>",
    "<STRING_LITERAL2>",
    "<METASYMBOL2>",
  };

}
