del _FIPA_Agent_97Stub.java
del FIPA_Agent_97.java
del FIPA_Agent_97Holder.java
del FIPA_Agent_97Helper.java
del _FIPA_Agent_97ImplBase.java

del *.class
del *.~jav
del jade\*.class
del jade\*.~jav
del jade\core\*.class
del jade\core\*.~jav
del jade\domain\*.class
del jade\domain\*.~jav
del jade\gui\*.class
del jade\gui\*.~jav
del jade\lang\acl\*.class
del jade\lang\acl\*.~jav
del jade\proto\*.class
del jade\proto\*.~jav
del jade\lang\acl\ACLParser.java
del jade\lang\acl\ACLParserConstants.java
del jade\lang\acl\ACLParserTokenManager.java
del jade\lang\acl\ASCII_CharStream.java
del jade\lang\acl\ParseException.java
del jade\lang\acl\Token.java
del jade\lang\acl\TokenMgrError.java
del jade\domain\AgentManagementParser.java
del jade\domain\AgentManagementParserConstants.java
del jade\domain\AgentManagementParserTokenManager.java
del jade\domain\ASCII_CharStream.java
del jade\domain\ParseException.java
del jade\domain\Token.java
del jade\domain\TokenMgrError.java

del examples\ex1\*.class
del examples\ex2\*.class
del examples\ex3\*.class
del examples\ex4\*.class
del examples\ex5\*.class
